spring.application.name=${SPRING_APP_NAME:SpringSecurity}
spring.security.user.name=${SECURITY_NAME:sa}
spring.security.user.password=${SECURITY_PASSWORD:12345}
logging.level.org.springframework.security=trace

